name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      cache-key-node_modules: ${{ steps.cache-node_modules-key.outputs.key }}
    steps:
      - uses: actions/checkout@v6

      - name: Generate cache key for node_modules
        id: cache-node_modules-key
        run: echo "key=${{ runner.os }}-ci-node_modules-${{ hashFiles('**/package-lock.json') }}" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ steps.cache-node_modules-key.outputs.key }}

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

  check:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        include:
          - name: Lint
            script: lint
          - name: Prettier
            script: prettier
          - name: Stylelint
            script: stylelint
    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Restore node_modules cache
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.cache-key-node_modules }}

      - name: Run Next.js typegen
        if: matrix.name == 'Lint'
        run: npx next typegen

      - name: Run ${{ matrix.name }}
        run: npm run ${{ matrix.script }}
